name: jest
description: Jest is a delightful JavaScript Testing Framework with a focus on simplicity. Works works Babel, TypeScript, Node, React, Angular, Vue and more!
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dash_agent: ^0.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
