name: vanna_ai
description:  Chat with your SQL database. Accurate Text-to-SQL Generation via LLMs using RAG.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dash_agent: ^0.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
